module.exports = {
  article: require('./article.js'),
  category: require('./category.js'),
  public: require('./public.js'),
  syndicate: require('./syndicate.js'),
  // attended: require('./attended.js'),
  // attending: require('./attending.js'),
  // bookmark: require('./bookmark.js'),
  // collection: require('./collection.js'),
  // comments: require('./comments.js'),
  // itinerary: require('./itinerary.js'),
  // note: require('./note.js'),
  // on_this_day: require('./on-this-day.js'),
  // photo: require('./photo.js'),
  // presentation: require('./presentation.js'),-
  // presented: require('./presented.js'),
  // project: require('./project.js'),
  // publication: require('./publication.js'),
  // reply: require('./reply.js'),
  // trip: require('./trip.js'),
};
